[book]
authors = ["hayashi3017"]
language = "ja"
multilingual = false
src = "src"
title = "Home"

# https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=no-section-label#html-renderer-options
[output.html]
no-section-label = true
