[book]
authors = ["hayashi3017"]
language = "en"
multilingual = false
src = "src"
title = "sequences"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
no-section-label = true
fold.enable = true
