name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build_base:
    uses: ./.github/workflows/reusable_build.yml
    with:
      cache-path: ./book
      dir-name: subjects
  build_foo:
    needs: build_base
    uses: ./.github/workflows/reusable_build.yml
    with:
      cache-path: ./book/foo
      dir-name: foo

  # https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#merging-multiple-artifacts
  merge:
    runs-on: ubuntu-latest
    needs: [build_base, build_foo]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-my-files
          pattern: artifact_*

  deploy:
    needs: merge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
      - name: test
        run: |
          ls -lart
          cd all-my-files && ls -lart
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bookshelf
          # artifact/配下にビルド資材が展開されている
          directory: artifact
          branch: main
          # 特に意味はないので将来的に削除しても問題ないと思う
          wranglerVersion: "3"
