name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build_base:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: home
  build_rust:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: rust
  build_systemd:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: systemd
  build_cloudflare:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: cloudflare
  build_html:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: html
  build_rfc:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: rfc
  build_javascript:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: javascript
  build_sql:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: sql
  build_sequences:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: sequences
  build_mysql:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: mysql
  build_algorithm:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: algorithm

  deploy:
    needs:
      [
        build_base,
        build_rust,
        build_systemd,
        build_cloudflare,
        build_html,
        build_rfc,
        build_javascript,
        build_sql,
        build_sequences,
        build_mysql,
        build_algorithm,
      ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      # https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./book
          pattern: artifact_*
          merge-multiple: true
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bookshelf
          directory: book
          branch: main
