name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build_base:
    uses: ./.github/workflows/reusable_build.yml
    with:
      cache-path: ./book
      dir-name: subjects
  build_foo:
    uses: ./.github/workflows/reusable_build.yml
    with:
      cache-path: ./book/foo
      dir-name: foo
  build_bar:
    uses: ./.github/workflows/reusable_build.yml
    with:
      cache-path: ./book/bar
      dir-name: bar
  upload:
    needs: [build_base, build_foo, build_bar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          path: ./book

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bookshelf
          # artifact/配下にビルド資材が展開されている
          directory: artifact
          branch: main
          # 特に意味はないので将来的に削除しても問題ないと思う
          wranglerVersion: "3"
