name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build_base:
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: home
  build_Rust:
    needs: build_base
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: Rust
  build_systemd:
    needs: build_Rust
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: systemd
  build_Cloudflare:
    needs: build_systemd
    uses: ./.github/workflows/reusable_build.yml
    with:
      dir-name: Cloudflare

  deploy:
    needs: [build_base, build_Rust, build_systemd, build_Cloudflare]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      # https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./book
          pattern: artifact_*
          merge-multiple: true
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bookshelf
          directory: book
          branch: main
