name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install mdbook
        run: |
          mkdir mdbook
          # for updates see: https://github.com/rust-lang/mdBook/tags
          curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build subjects
        uses: ./.github/workflows/reusable_build.yml
        with:
          cache-path: ./book
          dir-name: subjects
      - name: Build foo
        uses: ./.github/workflows/reusable_build.yml
        with:
          cache-path: ./book/foo
          dir-name: foo
      - name: Build bar
        uses: ./.github/workflows/reusable_build.yml
        with:
          cache-path: ./book/bar
          dir-name: bar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bookshelf
          # artifact/配下にビルド資材が展開されている
          directory: artifact
          branch: main
          # 特に意味はないので将来的に削除しても問題ないと思う
          wranglerVersion: "3"
